apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kourier
  namespace: kourier-system
spec:
  entryPoints:
  - web
  routes:
  - match: HostRegexp(`^.+\.yjgbg\.com$`)
    kind: Rule
    priority: 1
    services:
    - name: kourier-internal
      kind: Service
      namespace: kourier-system
      port: 80