apiVersion: v1
kind: Service
metadata:
  name: traefik-traefik
  namespace: kube-system
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-traefik
  namespace: kube-system
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`traefik.yjgbg.com`)
    observability:
      accesslogs: true
      metrics: true
      tracing: true
    services:
    - name: traefik-traefik
      kind: Service
      namespace: kube-system
      port: 8080