apiVersion: v1
kind: Service
metadata:
  name: traefik-traefik
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: traefik
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik