apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  storage:
    storageClass: local-path-retain
    size: 1Gi
---
# docker run --name phpmyadmin -d -e PMA_HOST=dbhost -p 8080:80 phpmyadmin
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: index
  namespace: postgres
spec:
  template:
    metadata:
      annotations:
        networking.knative.dev/server-httpoption: "enabled"
        autoscaling.knative.dev/window: "600s"
    spec:
      containers:
      - image: docker.m.daocloud.io/phpmyadmin:latest
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: postgres-pods
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: 
          requests:
            cpu: 100m
            memory: 100m