apiVersion: v1
kind: Namespace
metadata:
  name: kubectl
---
# docker run -e REMOTE_HOST=10.32.0.1 -e REMOTE_PORT=27017 -p 8080:80 port-forward
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: index
  namespace: kubectl
spec:
  template:
    spec:
      containers:
      - image: docker.m.daocloud.io/port-forward:latest
        name: phpmyadmin
        env:
        - name: REMOTE_PORT
          value: 6443
        - name: REMOTE_HOST
          value: 192.168.31.200
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: 
          requests:
            cpu: 200m
            memory: 200m