apiVersion: v1
kind: Namespace
metadata:
  name: solr
---
apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: zoo-solr
  namespace: solr
spec:
  version: 3.8.3
  replicas: 3
  deletionPolicy: Delete
  adminServerPort: 8080
  storage:
    resources:
      requests:
        storage: "100Mi"
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce
---
apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr
  namespace: solr
spec:
  deletionPolicy: Delete
  replicas: 3
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs-client
  version: 9.4.1
  zookeeperRef:
    name: zoo-solr
    namespace: nfs-client