apiVersion: v1
kind: Namespace
metadata:
  name: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: onaci/docker-http-https-echo:onaci
        ports:
        - containerPort: 80
        resources: 
          requests:
            cpu: 200m
            memory: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: ssh
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# 4. 创建 OAuth 中间件 (泛域名支持)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: github-oauth
  namespace: ssh
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth.svc.cluster.local:4180
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Redirect # 用于重定向到原始请求
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - Set-Cookie
      - Authorization
    authRequestHeaders:
      - Host
      - X-Forwarded-Proto
      - X-Forwarded-Host
---
# 6. 保护应用示例 (替换your-app)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: protected-app
  namespace: ssh
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`ssh.yjgbg.com`)  # 泛域名匹配
    kind: Rule
    services:
    - name: ssh-service  # 替换为实际服务
      port: 80
    middlewares:
    - name: github-oauth