apiVersion: kubedb.com/v1
kind: Kafka
metadata:
  name: broker-support-kafka
  namespace: knative-eventing
spec:
  replicas: 3
  version: 4.0.0
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: local-path
  storageType: Durable
  deletionPolicy: WipeOut