
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/kafbat/kafka-ui:latest
        name: kafka-ui
        env:
        - name: DYNAMIC_CONFIG_ENABLED
          value: true
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: 
          requests:
            cpu: 100m
            memory: 100m