apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql-demo
  namespace: mysql
spec:
  deletionPolicy: Delete
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: nfs-client
  storageType: Durable
  version: 8.0.32