apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql-demo
  namespace: mysql
spec:
  deletionPolicy: Delete
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: nfs-client
  storageType: Durable
  version: 9.1.0
---
# docker run --name phpmyadmin -d -e PMA_HOST=dbhost -p 8080:80 phpmyadmin
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: index
  namespace: mysql
spec:
  template:
    metadata:
      annotations:
        networking.knative.dev/server-httpoption: "enabled"
    spec:
      containers:
      - image: docker.m.daocloud.io/phpmyadmin:latest
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: mysql-demo-pods
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: 
          requests:
            cpu: 200m
            memory: 200m